[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/state"
  to = "/.netlify/functions/state"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/user-settings*"
  to = "/.netlify/functions/user-settings"
  status = 200

[[redirects]]
  from = "/api/gcal/*"
  to = "/.netlify/functions/gcal"
  status = 200

[[redirects]]
  from = "/api/icloud/*"
  to = "/.netlify/functions/icloud"
  status = 200
